### ISSUE TITLE
corsAllowedDomains should not affect serving of public files

### ISSUE THREAD

**Issue by tomas-polach** [archilogic-com/instant-api#3]
i've set `corsAllowedDomains` to `[ '0e6c7272.ngrok.io', 'localhost' ]`and i get the following error:

![index_js_-_3dio-floor-plan-app_-____archilogic_repositories_3dio-floor-plan-app_](https://user-images.githubusercontent.com/6619499/29432330-7a9cdb82-839b-11e7-8540-45d425ba9e11.png)

not sure if this is related to serving public files but it occurs on first request which happens to be a static html.

**Comment by tomas-polach** [comment]
it also crashes when i do not use the `corsAllowedDomains`option at all

**Comment by tomas-polach** [comment]
@AVGP any updates?

**Comment by AVGP** [comment]
Oh sorry, I forgot to close this. It was fixed in 7d82812e3d8f961573ceda7abe695c05991653e3
